### ISSUE TITLE
Add function block to store dot files

### ISSUE THREAD

**Issue by blumenthal** [blumenthal/ubx_robotscenegraph#32]
As parameter a subgraph id has to be passed to allow to visualize only a subset of the graph. Otherwise visualization can get a mess.

**Comment by tompe17** [comment]
The commands to print must be very short.  p() is nearly the maximum and a bit inconvenient since you have to use shift. Just so you do not miss half the point here.  Print a smaller part and print it by pressing a minimal amount of keys.

**Comment by blumenthal** [comment]
To clarify this: there are two use cases for the same block:

1. Invocation via JSON API. It will be possible for an external program to trigger the print and obtain the file path as a result. Relevant e.g. for visualization in OpenEASE (KnowRob).

2. Invocation via Lua interactive terminal. This will be similar to the current Lua function for printing ``p()``. e.g. ``pa()``. The Lua function will wrap the JSON messaging and can be very short.

**Comment by blumenthal** [comment]
Cf. https://github.com/blumenthal/brics_3d_function_blocks/commit/341d23c9342f35cd3ec245bc9640dcbae7d4e132
