### ISSUE TITLE
Zyre bridge can hang with: Error parsing JSON payload!

### ISSUE THREAD

**Issue by blumenthal** [blumenthal/ubx_robotscenegraph#33]
Procedure to replicate
----------------------------

in terminal 1:
```
./run_sherpa_world_model.sh --no-ros
s()
```

in terminal 2:

```
cd examples/json_api/
python zyre_add.py new_node.json 
python zyre_add.py add_node.py 
python zyre_add.py new_node.json 
```
NOTE: ``python zyre_add.py add_node.py`` sends no-JSON conform data to the bridge. Essentially it send python code code that cannot be handled. Unfortunatley the bridege starts to hang and no further command is being processed e.g.`` python zyre_add.py new_node.json`` 

The console output of the SWM is:

```
[zyre_bridge]: SHOUT received from swm_zyre_client.
Error parsing JSON payload! line 1: '[' or '{' expected near '(
```

**Comment by nhuebel** [comment]
closed with fix in ubx/zyre_bridge
