### ISSUE TITLE
Update of one attribute value should not remove all other attributes

### ISSUE THREAD

**Issue by tompe17** [blumenthal/ubx_robotscenegraph#34]
Have a flag maybe on the update-attribute command to tell if all attributes should be removed or not.

Having it as it is now makes the API to complicated and harder to use then it needs to be.

**Comment by blumenthal** [comment]
Good point. Currently the work flow is:

1. get all attributes of a node
2. update them to your need
3. set them again

For this flag/mode I see more than two options:

| ``updateMode`` | Description | 
|----------------------|----------------
| OVERWRITE     |  Same as right now. Existing attributes are replaced. | 
| APPEND            | New attributes are appended to existing one. Keys might appear multiple times (e.g. multiple ``rsg:agent_policy`` = ...).  | 
| UPDATE            | For each attribute it is checked if it exists. If so the value gets updated, other wise it is appended. |

**Comment by tompe17** [comment]
And that workflow is of course not working if two programs change different attributes at the same time. So that should not be the work flow.  If you have that work flow you must have some locking.

So OVERWITE maybe should not be an alternative...

For now I need UPDATE so that is most important.

**Comment by nhuebel** [comment]
Locking mechanisms are not practical for distributed systems with (likely) poor connectivity. You would first have some handshakes to ensure the locking of the data on each agent, then handshakes to ensure the changes happened everywhere, and finally handshakes to ensure that all changes are committed and to unlock the data.

There is a reason why git does it differently. The question is how we would deal with potential "merge conflicts". E.g., we can strictly apply changes according to their time stamp (assuming that it is very unlikely that changes will be made at exactly the same time) or we could keep copies for changes of each agent.

Of course, maybe we should first answer the question if there is a use case that can produce such a conflict.

**Comment by tompe17** [comment]
I vote for just update the things specified. Better then now and you have to be aware of the limitations. Usually two programs do not update the same attribute.

**Comment by blumenthal** [comment]
I agree.

Just for clarification. A change of attributes is accompanied by a time stamp. In case it is not part of the message it automatically takes the current time. This means changes are applied if they adhere to a chronological order. E.g. if an update from another World Model Agent arrives with an older stamp than the currently stored attribute, the change will not be applied. 

The borderline case is when a time stamp is **exactly** the same. In the current implementation the change will be applied and overrides the existing one. Thus, the last message for an attribute change in the queue takes precedence.

**Comment by nhuebel** [comment]
I also agree that in SHERPA we will most likely not run into this problem since usually agents only update attributes in their own scope/subgraph. So let's document this behaviour and go for the proposed solution.

Sebastian, let's put this on the agenda with Herman when you come here. Maybe we can come up with a good solution for the future.

**Comment by tompe17** [comment]
Well, I would like to have the option to ignore the timestamp and always change. That is because a common failure mode is that the clocks are not synchronized. So usually you want to write the programs so that this does not matter.  But the proposes implementation will work better than now so pleas fix it soon.

**Comment by tompe17** [comment]
And some of my use cases are that the BG change some value and all other agents read this value. That is for me the most common use case.

**Comment by blumenthal** [comment]
In your concrete use case is it only the BG writing to it? Btw, I moved it up on the TODO list

**Comment by tompe17** [comment]
In the demo scenarios BG need to write. But also maybe the Wasp need to write battery and Artva values.

**Comment by blumenthal** [comment]
Yes, but each one will write to *their* own nodes, right? If yes, we do not have conflicting changes of attributes.

**Comment by tompe17** [comment]
Well, yes. But the BG might read the battery value of all vehicles.

**Comment by blumenthal** [comment]
That case should be fine even with a time offset in the clocks.

**Comment by blumenthal** [comment]
Added to brics_3d in commit: https://github.com/brics/brics_3d/commit/efd96f72f6d5e5ece870840954c73a16f424b265

**Comment by blumenthal** [comment]
Example (payload): 

```
{
  "@worldmodeltype": "RSGUpdate",
  "operation": "UPDATE_ATTRIBUTES",
  "updateMode": "UPDATE",
  "node": {
    "@graphtype": "Node",
    "id": "41bba5aa-ebab-45ec-86a9-c37524afd550", 
    "attributes": [
          {"key": "ambient_temperature", "value": "-6°C"}
    ]
  }
}
```
