### ISSUE TITLE
Store list of strings in attribute to node

### ISSUE THREAD

**Issue by tompe17** [blumenthal/ubx_robotscenegraph#37]
I need to store a list of strings as an attribute to a node.

How do I do it? The obvious way to enocde it as json did not work.

**Comment by blumenthal** [comment]
Within an attribute it is possible to replace a JSON string for the ``value`` with any valid JSON object. Including lists

The following **list** should work:

```javascript

            {
               "key" : "capabilities",
               "value" : ["scan-ground-single", "init-collect-data"]
            }
```

this is how an object look like **object**:

```javascript
          {
               "key": "sherpa:command_pointing_gesture", 
               "value": {
                   "direction":[0.3, 0.7, 0.0]
               }
          }
```
