### ISSUE TITLE
Print only tree under agent node - pa()

### ISSUE THREAD

**Issue by tompe17** [blumenthal/ubx_robotscenegraph#38]
Define pa() to print only the tree under the agent node.

**Comment by blumenthal** [comment]
This is related related to #32. The only difference how it is called it. the ``pa()`` is a Lua call while in #32 the JSON API would be used to trigger externally. I think it is possible to call the JSON API also from Lua directly. In that case we only need a single implementation.

**Comment by blumenthal** [comment]
It is indeed possible. So any further discussion will be in #32.
