### ISSUE TITLE
update of attribute fails when the attribute have the same value

### ISSUE THREAD

**Issue by tompe17** [blumenthal/ubx_robotscenegraph#43]
That is not the expected behaviour. One program want to set the attribute to a specific value. That is now not possible since setting it might result in a failure. And we do not know what caused the failure. So proper error handling is impossible,

The update should not fail.

**Comment by blumenthal** [comment]
Fixed in https://github.com/brics/brics_3d/commit/c1764239a2ab7e027bdd430ecc52dcc73c381569.
