### ISSUE TITLE
Cannot get Mediator ID

### ISSUE THREAD

**Issue by jocacace** [blumenthal/ubx_robotscenegraph#50]
Using the "add_image" API, is impossible to get the mediator ID:

This is the output on the API side:

[swm_zyre_client] send_json_message: message = {"metamodel": "sherpa_mgs", "model": "http://kul/query_mediator_uuid.json", "type": "query_mediator_uuid", "payload": {"UID": "22c06ddf-aa48-6744-b8c4-f8232c60ccc5"}}:
[swm_zyre_client] Timeout! No query answer received.
[swm_zyre_client] Stopping zyre node.
[swm_zyre_client] Destroying component.
[] Received no reply for mediator_id query.
[] [ERROR] Cannot get Mediator ID. Is the Mediator started?

**Comment by blumenthal** [comment]
Hello Jonathan,

I think your version of the mediator is outdated since the ``query_mediator_uuid`` was recently added in this commit: https://github.com/maccradar/sherpa-com-mediator/commit/a972085bcdba0c0125b8900b7f1a96d8aceef6d8.

Can you please pull and build your mediator again?

Sebastian

**Comment by jocacace** [comment]
Good, a very simple solution :).

I should everytime test the state of git before post issues. Now it works,
thank you!

Jonathan Cacace

2016-12-19 9:09 GMT+01:00 Sebastian Blumenthal <notifications@github.com>:

**Comment by blumenthal** [comment]
Good to know it is solved. ;-)
